name: calculator
description: Calculator example
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.0
  intl: ^0.18.0
  math_expressions: ^2.4.0
  meta: ^1.8.0
  provider: ^6.0.5
  yaru: ^1.2.1
  yaru_icons: ^2.3.0
  yaru_widgets: ^3.4.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
